name: Check Multiple GitHub User Tokens

on: [push]

jobs:
  check-users:
    runs-on: ubuntu-latest
    steps:
      - name: Check Multiple Tokens
        env:
          TOKEN1: ${{ secrets.GITHUB_TOKEN }}
          TOKEN2: ${{ secrets.DAE_GITHUB_TOKEN }}
          
        run: |
          TOKENS=($TOKEN1 $TOKEN2 $TOKEN3)

          # 각 토큰에 대해 사용자 정보 조회
          for TOKEN in "${TOKENS[@]}"
          do
            if [ -n "$TOKEN" ]; then
              USER_INFO=$(curl -H "Authorization: token $TOKEN" https://api.github.com/user)
              echo "User Info: $USER_INFO"
            else
              echo "Token is empty, skipping..."
            fi
          done
